DROP DATABASE DIA030225;

CREATE DATABASE DIA030225;

USE DIA030225;

CREATE TABLE Autores (
    AutorID INT PRIMARY KEY AUTO_INCREMENT ,
    NombreAutor
    VARCHAR(100)
);

CREATE TABLE Libros (
    LibroID INT PRIMARY KEY AUTO_INCREMENT,
    NombreLibro VARCHAR(100),
    Autor VARCHAR(100)
);

-- CREAR UN TRIGGER QUE AL INSERTAR UN REGISTRO EN LA TABLA DE LIBROS LO INSERTE TAMBIEN EN LA TABLA DE AUTOR
DELIMITER  $$
CREATE TRIGGER InsertarEnAutor
AFTER INSERT ON Libros
FOR EACH ROW
BEGIN
	INSERT INTO Autores(NombreAutor) VALUES (new.Autor);
END $$
DELIMITER ;


INSERT INTO Libros(NombreLibro, Autor) VALUES ('PEPITO GRILLO','EDUARDO');

SELECT * FROM Libros;
SELECT * FROM Autores;


-- cuando se borre un autro que se borren los libros que tenga ese autor
DELIMITER  $$
CREATE TRIGGER InsertarEnAutor
AFTER DELETE ON Autores
FOR EACH ROW
BEGIN
	DELETE Libro FROM new.Autor;
END $$
DELIMITER ;
