CREATE DATABASE CLASE20241217_2;

CREATE TABLE CLASE20241217_2.TD_EQUIPOS(
ID_EQUIPO INT auto_increment PRIMARY KEY,
NOMBRE_EQUIPO VARCHAR(100),
DESC_EQUIPO VARCHAR(1000),
ID_TIPO_COMPETICION INT
);


CREATE TABLE CLASE20241217_2.TD_TIPO_COMPETICION(
ID_TIPOCOMP INT auto_increment PRIMARY KEY,
NOMBRE_EQUIPO VARCHAR(100),
IMPORTANCIA INT
);

INSERT INTO CLASE20241217_2.TD_EQUIPOS(ID_EQUIPO, NOMBRE_EQUIPO, DESC_EQUIPO ,ID_TIPO_COMPETICION)
VALUES
(1,"BETIS","DESCENSO",1),
(2,"MIJAS","DE PUEBLO",5),
(3,"ATLETI","CAMPIONT",4),
(4,"GETAFE","SUCIO",3),
(5,"GIRONA","DECENTE",2),
(6,"BILBAO","VASCOS",6),
(7,"MALAGA","SEGUNDOMEJOR",4),
(8,"MADRID","ELMEJOR",2);


INSERT INTO CLASE20241217_2.TD_TIPO_COMPETICION(ID_TIPOCOMP, NOMBRE_EQUIPO , IMPORTANCIA)
VALUES
(1,"CONFERENCE",3),
(2,"CHAMPIONS",1),
(3,"PRIMERA",4),
(4,"SEGUNDA",5),
(6,"EUROPA",2);


select E.NOMBRE_EQUIPO, C.NOMBRE_EQUIPO, C.IMPORTANCIA
FROM CLASE20241217_2.TD_EQUIPOS E
INNER JOIN CLASE20241217_2.TD_TIPO_COMPETICION TC
ON E.ID_TIPO_COMPETICION = TC.ID_TIPOCOMP;