-- Ejercicio 1 creamos la base de datos 
CREATE DATABASE PRUEBA1CLASE;


-- Ejercicio 2 creamos tablas y sus campos
USE PRUEBA1CLASE;

CREATE TABLE AUTORES(
	ID_AUTOR INT primary KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    AUTOR varchar(100),
    NACIONALIDAD VARCHAR(100),
    FEC_NACIMIENTO VARCHAR(100)
);

CREATE TABLE LIBROS (
	ID_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100),
    ID_AUTOR INT,
    ID_EDITORIAL INT,
    ID_CATEGORIA INT,
    ANO_PUBLICACION INT
    
);



CREATE TABLE EDITORIALES (
	ID_EDITORIAL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_EDITORIAL VARCHAR(100),
    PAIS_EDITORIAL VARCHAR(100)
);

CREATE TABLE CATEGORIAS(
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(100)
);

CREATE TABLE USUARIOS(
	ID_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(100),
    EMAIL VARCHAR(100),
    FEC_REGISTRO VARCHAR(100)
);

CREATE TABLE PRESTAMOS (
	ID_PRESTAMO INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIBRO VARCHAR(100),
    ID_USUARIO VARCHAR(100),
    FEC_PRESTAMO VARCHAR(100),
    FEC_DEVOLUCION VARCHAR(100),
);

CREATE TABLE RESENAS (
	ID_RESEÑA INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIBRO VARCHAR(100),
    ID_USUARIO VARCHAR(100),
    CLASIFICACION VARCHAR(100), -- ENTRE 1 Y 5 VALORES
    COMENTARIO VARCHAR(100),
    FEC_RESENA VARCHAR(100),
);

-- 3. CREA LAS SIGUINETES RESTRICCIONES

-- 4. INSERTS DE ALMENOS 5 REGISTROS
INSERT INTO AUTORES ( ID_AUTOR, NOMBRE_AUTOR, NACIONALIDAD, FEC_NACIMIENTO) 
VALUES (1,'MANOLO', 'AMERICA', '10/10/2000');
INSERT INTO AUTORES ( ID_LIBRO, NOMBRE_AUTOR, NACIONALIDAD, FEC_NACIMIENTO) 
VALUES (2, 'PAULA', 'ESPAÑA', '25/12/2005');
INSERT INTO AUTORES ( ID_LIBRO, NOMBRE_AUTOR, NACIONALIDAD, FEC_NACIMIENTO) 
VALUES (3, 'LAURA', 'FRANCIA', '15/08/1978');
INSERT INTO AUTORES ( ID_LIBRO, NOMBRE_AUTOR, NACIONALIDAD, FEC_NACIMIENTO) 
VALUES (4, 'PEPA', 'SINGAPUR', '26/09/1999');
INSERT INTO AUTORES ( ID_LIBRO, NOMBRE_AUTOR, NACIONALIDAD, FEC_NACIMIENTO) 
VALUES (5, 'ANGEL', 'CHINA', '31/01/1992');

INSERT INTO LIBROS( ID_LIBRO, TITULO, ID_AUTOR, ID_EDITORIAL, ID_CATEGORIA, ANO_PUBLICACION) 
VALUES (1, 'EL LIBRO DE LA VIDA', '12/12/1980');
INSERT INTO LIBROS(ID_LIBRO, TITULO, ID_AUTOR, ID_EDITORIAL, ID_CATEGORIA, ANO_PUBLICACION) 
VALUES (2, 'MANOLO Y SU CABALLO', '25/05/2001');
INSERT INTO LIBROS(ID_LIBRO, TITULO, ID_AUTOR, ID_EDITORIAL, ID_CATEGORIA, ANO_PUBLICACION) 
VALUES (3, 'HISTORIA DEL REAL MADRID', '14/09/25');
INSERT INTO LIBROS(ID_LIBRO, TITULO, ID_AUTOR, ID_EDITORIAL, ID_CATEGORIA, ANO_PUBLICACION) 
VALUES (4,'INDIOS EN PATERAS', '//');
INSERT INTO LIBROS(ID_LIBRO, TITULO, ID_AUTOR, ID_EDITORIAL, ID_CATEGORIA, ANO_PUBLICACION) 
VALUES (5, 'MANOLO PERDIO SU CABALLO', '//');

INSERT INTO EDITORIALES( ID_EDITORIAL, NOMBRE_EDITORIAL, PAIS_EDITORIAL) 
VALUES (1, 'PACHON', 'ESPAÑA');
INSERT INTO EDITORIALES(ID_EDITORIAL, NOMBRE_EDITORIAL, PAIS_EDITORIAL) 
VALUES (2, 'PERUANOS ENTRETAIMENT', 'PERU');
INSERT INTO EDITORIALES(ID_EDITORIAL, NOMBRE_EDITORIAL, PAIS_EDITORIAL) 
VALUES (3, 'PIXAR', 'COLOMBIA');
INSERT INTO EDITORIALES(ID_EDITORIAL, NOMBRE_EDITORIAL, PAIS_EDITORIAL) 
VALUES (4, 'NAPO', 'COLOMBIA');
INSERT INTO EDITORIALES(ID_EDITORIAL, NOMBRE_EDITORIAL, PAIS_EDITORIAL) 
VALUES (5'SAMOR', 'FRANCIA');

INSERT INTO CATEGORIAS(ID_CATEGORIA, NOMBRE_CATEGORIA) 
VALUES (1);
INSERT INTO CATEGORIAS(ID_CATEGORIA, NOMBRE_CATEGORIA) 
VALUES (2);
INSERT INTO CATEGORIAS(ID_CATEGORIA, NOMBRE_CATEGORIA) 
VALUES (3);
INSERT INTO CATEGORIAS(ID_CATEGORIA, NOMBRE_CATEGORIA) 
VALUES (4);
INSERT INTO CATEGORIAS(ID_CATEGORIA, NOMBRE_CATEGORIA) 
VALUES (5);


INSERT INTO USUARIOS( ID_USUARIO, NOMBRE_USUARIO, EMAIL, FEC_REGISTRO) 
VALUES (1);
INSERT INTO USUARIOS( ID_USUARIO, NOMBRE_USUARIO, EMAIL, FEC_REGISTRO) 
VALUES (2);
INSERT INTO USUARIOS( ID_USUARIO, NOMBRE_USUARIO, EMAIL, FEC_REGISTRO) 
VALUES (3);
INSERT INTO USUARIOS( ID_USUARIO,NOMBRE_USUARIO, EMAIL, FEC_REGISTRO) 
VALUES (4);
INSERT INTO USUARIOS( ID_USUARIO,NOMBRE_USUARIO, EMAIL, FEC_REGISTRO) 
VALUES (5);

INSERT INTO PRESTAMOS(ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FEC_PRESTAMO, FEC_DEVOLUCION) 
VALUES (1);
INSERT INTO PRESTAMOS(ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FEC_PRESTAMO, FEC_DEVOLUCION) 
VALUES (2);
INSERT INTO PRESTAMOS(ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FEC_PRESTAMO, FEC_DEVOLUCION) 
VALUES (3);
INSERT INTO PRESTAMOS(ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FEC_PRESTAMO, FEC_DEVOLUCION) 
VALUES (4);
INSERT INTO PRESTAMOS(ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FEC_PRESTAMO, FEC_DEVOLUCION) 
VALUES (5);

INSERT INTO RESENAS( ID_RESEÑA , ID_LIBRO, ID_USUARIO, CLASIFICACION ,  COMENTARIO, FEC_RESEÑA) 
VALUES (1);
INSERT INTO RESENAS(ID_RESEÑA , ID_LIBRO, ID_USUARIO, CLASIFICACION ,  COMENTARIO, FEC_RESEÑA) 
VALUES (2);
INSERT INTO RESENAS(ID_RESEÑA , ID_LIBRO, ID_USUARIO, CLASIFICACION ,  COMENTARIO, FEC_RESEÑA) 
VALUES (3);
INSERT INTO RESENAS(ID_RESEÑA , ID_LIBRO, ID_USUARIO, CLASIFICACION ,  COMENTARIO, FEC_RESEÑA) 
VALUES (4);
INSERT INTO RESENAS(ID_RESEÑA , ID_LIBRO, ID_USUARIO, CLASIFICACION ,  COMENTARIO, FEC_RESEÑA) 
VALUES (5);

-- 5.1 

