use CLASE20250109;

create table NOTAS (
ALUMNOS VARCHAR (100),
ASIGNATURAS VARCHAR (100),
NOTA VARCHAR (100)
);

INSERT INTO NOTAS (ALUMNOS, ASIGNATURAS, NOTA) VALUE ('NOAH','BBDD','8');
INSERT INTO NOTAS (ALUMNOS, ASIGNATURAS, NOTA) VALUE ('NOAH','FOL','9');
INSERT INTO NOTAS (ALUMNOS, ASIGNATURAS, NOTA) VALUE ('CARLOS','BBDD','7');
INSERT INTO NOTAS (ALUMNOS, ASIGNATURAS, NOTA) VALUE ('CARLOS','FOL','8');
INSERT INTO NOTAS (ALUMNOS, ASIGNATURAS, NOTA) VALUE ('IVAN','BBDD','6');
